name: SonarCloud

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: -Dsonar.coverageReportPaths=coverage.xml
          projectBaseDir: .

        env:
          DOTNET_ROOT: /home/runner/.dotnet
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
