name: SonarCloud
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build and test
        run: |
          dotnet build ./Streetcode/Streetcode.sln
          dotnet test ./Streetcode/Streetcode.sln --logger "trx;LogFileName=testresults.trx"
      - name: Code Coverage
        run: |
          dotnet tool install -g coverlet.console
          dotnet test ./Streetcode/Streetcode.sln --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
          cp -r ./Streetcode/**/coverage.cobertura.xml $GITHUB_WORKSPACE/coverage.cobertura.xml
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        with:
          args: >
            -Dsonar.organization=ita-social-projects
            -Dsonar.projectKey=ita-social-projects_StreetCode
            -Dsonar.cs.opencover.reportsPaths=coverage.cobertura.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
