name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # To prevent permission issues

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore ./Streetcode/Streetcode.sln

      - name: Build
        run: dotnet build ./Streetcode/Streetcode.sln --configuration Release --no-restore

      - name: Test and Code Coverage
        run: dotnet test ./Streetcode/Streetcode.sln --configuration Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Install coverallsapp/github-action
        run: dotnet tool install --global coveralls.net

      - name: Upload Code Coverage to Coveralls
        run: dotnet /root/.dotnet/tools/coveralls --opencover -i ./Streetcode/**/coverage.opencover.xml --repo-token ${{ secrets.GITHUB_TOKEN }}
