name: SonarCloud

on: [push]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v1.8
        with:
          args: >
            -Dsonar.organization=ita-social-projects
            -Dsonar.projectKey=ita-social-projects_StreetCode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
