name: SonarCloud

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore $(Parameters.RestoreBuildProjects)

      - name: Prepare analysis on SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          organization: 'ita-social-projects'
          projectKey: 'ita-social-projects_StreetCode'
          projectName: 'StreetCode'

      - name: Build
        run: dotnet build $(Parameters.RestoreBuildProjects) --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Test
        run: dotnet test $(Parameters.projects) --collect "Code Coverage"

      - name: Run Code Analysis
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish Quality Gate Result
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
